"""
PCS Business OS - Retrieval-Augmented Generation (RAG) and Semantic Search Routes
File: /app/routes/rag.py
"""

import logging
from datetime import datetime
from typing import List, Optional
from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from pydantic import BaseModel, Field

from app.core.dependencies import get_current_active_user
from app.models.user import UserResponse, PyObjectId
from app.services.rag_service import RAGService
from app.services.embedding_service import EmbeddingService

logger = logging.getLogger("pcs-business-os.routes.rag")

router = APIRouter()


class QueryRequest(BaseModel):
    """Payload schema for executing a grounded context-search query."""
    query: str = Field(..., min_length=1, description="The natural language query or question")
    conversation_id: Optional[str] = Field(default=None, description="Identifier to group queries in a single chat thread")
    file_id_filter: Optional[str] = Field(default=None, description="Optionally restrict search to a specific uploaded document")
    limit: int = Field(default=5, ge=1, le=20, description="Maximum number of context chunks to retrieve")


class ReferenceItem(BaseModel):
    """Information about a specific document source chunk utilized in answering."""
    file_id: str = Field(..., description="Foreign key reference of the file container")
    chunk_index: int = Field(..., description="Index of the chunk in the document flow")
    score: float = Field(..., description="Cosine similarity score or relevance metric of the matching block")
    snippet: str = Field(..., description="Short preview snippet of the matched text")


class RAGQueryResponse(BaseModel):
    """Payload schema returned to clients after grounding queries in context."""
    success: bool = Field(default=True)
    query: str = Field(..., description="The original query executed")
    answer: str = Field(..., description="The context-grounded response text generated by Google Gemini")
    references: List[ReferenceItem] = Field(default_factory=list, description="Source context documents matched in vector search")


class RAGHistoryItem(BaseModel):
    """Interaction history record schema."""
    id: PyObjectId = Field(..., alias="_id")
    user_id: PyObjectId = Field(..., description="Associated user ID")
    conversation_id: str = Field(..., description="Chat thread identifier")
    query: str = Field(..., description="Original user query")
    answer: str = Field(..., description="Generated answer text")
    references: List[ReferenceItem] = Field(default_factory=list, description="References used")
    chunks_used_count: int = Field(..., description="Total semantic chunks supplied to Gemini")
    created_at: datetime = Field(..., description="Timestamp of the query event")

    model_config = {
        "populate_by_name": True,
        "arbitrary_types_allowed": True,
        "json_encoders": {ObjectId: str}
    }


class IndexingRequest(BaseModel):
    """Payload schema to request manual indexing of a file asset."""
    file_id: str = Field(..., description="Hex string representing the file asset's MongoDB ObjectId")


class IndexingResponse(BaseModel):
    """Detailed result status for document indexing operations."""
    success: bool = Field(..., description="True if text extraction and embedding generation completed successfully")
    chunks_count: int = Field(..., description="Total number of structural chunks created and vectorized")
    message: str = Field(..., description="Status feedback message")


@router.post(
    "/query",
    response_model=RAGQueryResponse,
    status_code=status.HTTP_200_OK,
    summary="Execute grounded query search (Active user only)"
)
async def query_documents(
    request: Request,
    payload: QueryRequest,
    current_user: UserResponse = Depends(get_current_active_user)
):
    """
    Accepts a natural language query, performs semantic vector similarity matching on database chunks,
    and forwards the grounded text segments as context along with the user's question to Google Gemini.
    """
    db = request.app.state.db
    if db is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database service is currently offline."
        )

    try:
        result = await RAGService.answer_query(
            db=db,
            user_query=payload.query,
            uploaded_by=ObjectId(current_user.id),
            conversation_id=payload.conversation_id,
            file_id_filter=payload.file_id_filter,
            limit=payload.limit
        )
        return result
    except ValueError as e:
        logger.error(f"RAG search query error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.critical(f"Unexpected RAG processing failure: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal error occurred while generating AI grounded response."
        )


@router.get(
    "/history",
    response_model=List[RAGHistoryItem],
    summary="List past query interactions (Active user only)"
)
async def list_rag_history(
    request: Request,
    conversation_id: Optional[str] = Query(None, description="Filter history by conversation/thread ID"),
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    current_user: UserResponse = Depends(get_current_active_user)
):
    """
    Returns recorded interaction events of user query questions and AI grounded responses.
    Allows drilling down into specific chat conversation threads.
    """
    db = request.app.state.db
    if db is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database service is currently offline."
        )

    # Filter interactions based on owner ID and optional session parameters
    query = {"user_id": ObjectId(current_user.id)}
    if conversation_id:
        query["conversation_id"] = conversation_id

    cursor = db.rag_history.find(query).skip(skip).limit(limit).sort("created_at", -1)
    results = await cursor.to_list(length=limit)
    return results


@router.post(
    "/index",
    response_model=IndexingResponse,
    status_code=status.HTTP_200_OK,
    summary="Manually trigger document text extraction and embedding generation"
)
async def index_file_asset(
    request: Request,
    payload: IndexingRequest,
    current_user: UserResponse = Depends(get_current_active_user)
):
    """
    Triggers backend extraction, semantic segmentation, and vector embedding indexing
    for a uploaded file asset inside MongoDB chunks collection.
    """
    db = request.app.state.db
    if db is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database service is currently offline."
        )

    # 1. Look up file metadata record
    try:
        file_obj_id = ObjectId(payload.file_id)
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid file ID format."
        )

    file_doc = await db.files.find_one({"_id": file_obj_id})
    if not file_doc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The requested file asset record could not be found."
        )

    # 2. Check access rights
    if str(file_doc["uploaded_by"]) != str(current_user.id) and \
       current_user.role not in ["admin", "manager"] and not current_user.is_superuser:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied: You do not own this file asset."
        )

    physical_path = file_doc["storage_path"]
    if not os.path.exists(physical_path) if hasattr(os, "path") else True:
        # Import os defensively
        import os
        if not os.path.exists(physical_path):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="The physical document is missing from server storage."
            )

    # 3. Trigger processing and vector indexing
    try:
        result = await EmbeddingService.process_and_index_file(
            db=db,
            file_id=file_obj_id,
            physical_path=physical_path,
            uploaded_by=ObjectId(current_user.id)
        )
        return result
    except ValueError as e:
        logger.error(f"Document indexing failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.critical(f"Critical error during indexing operation: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An internal error occurred while indexing document: {str(e)}"
        )
